lisp.js:
    - src/javascript/wrapper/_header.js
    - support/vendor/Class.js
    - support/vendor/sprintf.js
    - src/javascript/utils/json.js
    - src/javascript/utils/tolisp.js
    - src/javascript/utils/utils.js
    - src/javascript/utils/chartable.js
    - src/javascript/utils/stream.js
    - src/javascript/lisp/utils.js
    - src/javascript/lisp/Env.js
    - src/javascript/lisp/Symbol.js
    - src/javascript/lisp/Keyword.js
    - src/javascript/lisp/Macro.js
    - src/javascript/parse/utils.js
    - src/javascript/parse/parse.js
    - src/javascript/config.js
    - src/javascript/core/macros.js
    - src/javascript/core/functions.js
    - src/javascript/lisp.js
    - src/javascript/wrapper/_footer.js

core.lisp:
    - src/lisp/macros.lisp
    - src/lisp/functions.lisp
