(setq window.onload
	(lambda (e)
		(let ((lst    (document.getElementById "list"))
			  (add-li (lambda (text)
						(let ((li (document.createElement "li")))
							(li.appendChild (document.createTextNode text))
							(lst.appendChild li)))))
			(add-li (join " " (list "(/ 10 2)" "=" (/ 10 2))))
			(add-li (join " " (list "(/ 20 2 3)" "=" (/ 20 (to-number "2") (to-string 3)))))
			(add-li (join " " (list "(+ (* 2 3) (* 4 5))" "=" (+ (* 2 3) (* 4 (1+ 4)))))))))
